/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AjvError {
  message: string
  instancePath: string
  schemaPath: string
}
export declare class Ajv {
  constructor()
  addSchema(schema: any, key?: string | undefined | null): void
  addFormat((name: string, format: (data: string) => boolean)): void
  addKeyword((name: string, definition: (schema: any, data: any) => boolean)): void
  clearCache(): void
  compile(schema: any, draftUri?: string | undefined | null, validateFormats?: boolean | undefined | null): NapiValidator
}
export declare class NapiValidator {
  validate(data: any): Array<AjvError> | null
  validateBuffer(buffer: Buffer): Array<AjvError> | null
  isValidBuffer(buffer: Buffer): boolean
}
