/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ValidationResult {
  valid: boolean
  errors?: Array<AjvError>
}
export interface AjvError {
  message: string
  instancePath: string
  schemaPath: string
}
export declare class Ajv {
  constructor()
  addSchema(schema: any, key?: string | undefined | null): void
  compile(schema: any, draftUri?: string | undefined | null): NapiValidator
}
export declare class NapiValidator {
  validate(data: any): ValidationResult
  validateString(dataStr: string): ValidationResult
  validateBuffer(buffer: Buffer): ValidationResult
  /** Fast path - only returns validity, no error details */
  isValidBuffer(buffer: Buffer): boolean
  /** Fast path for string input - only returns validity */
  isValidString(dataStr: string): boolean
}
